### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by tavishs98** [CubicalBatch/deaddit#2]
I'm trying to follow the usage instructions and have both the deaddit and Ollama API up and running, but when running loader.py, I am getting this:

```
C:\Users\***\Downloads\deaddit>python deaddit\loader.py --subdeaddit
2024-04-29 20:38:34.007 | INFO     | __main__:create_subdeaddit:174 - Creating a new subdeaddit...
2024-04-29 20:38:34.008 | INFO     | __main__:send_request:23 - Sending prompt to the server http://localhost:11434/v1/... Set environment variable OPENAI_API_URL to change the server URL.
2024-04-29 20:38:37.998 | INFO     | __main__:send_request:33 - Response received from the local OLLaMA server.
2024-04-29 20:38:37.999 | INFO     | __main__:parse_data:53 - Received {
"name": "PlanCraft",
"description": "PlanCraft is a community for individuals who want to optimize their productivity and workflow by designing and planning out their daily, weekly, and long-term projects.\nWhether you're a student trying to manage your coursework, an entrepreneur looking to streamline your business operations, or simply someone looking to boost their personal effectiveness, PlanCraft provides a supportive environment for sharing strategies, seeking advice, and celebrating successes."<|eot_id|><|start_header_id|>}
2024-04-29 20:38:37.999 | WARNING  | __main__:parse_data:68 - Failed to parse JSON data from the API response.
2024-04-29 20:38:37.999 | INFO     | __main__:ingest:98 - POSTing data to http://localhost:5000/api/ingest
2024-04-29 20:38:38.000 | INFO     | __main__:ingest:100 - Data to be POSTed: {}
2024-04-29 20:38:40.008 | INFO     | __main__:ingest:102 - Response received from http://localhost:5000/api/ingest
2024-04-29 20:38:40.009 | INFO     | __main__:ingest:103 - Status code: 400
2024-04-29 20:38:40.010 | INFO     | __main__:ingest:104 - Response content: b'{\n  "error": "Invalid subdeaddit data"\n}\n'
2024-04-29 20:38:40.011 | INFO     | __main__:main:332 - No flag specified. 5% chance of creating a post, 95% chance of creating a comment.
2024-04-29 20:38:40.011 | INFO     | __main__:create_comment:213 - Creating a new comment...
2024-04-29 20:38:42.028 | INFO     | __main__:create_comment:222 - Retrieved 0 posts from the API.
Traceback (most recent call last):
  File "C:\Users\***\Downloads\deaddit\deaddit\loader.py", line 340, in <module>
    main()
  File "C:\Users\***\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\***\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\***\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\***\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\***\AppData\Local\Programs\Python\Python310\lib\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\***\Downloads\deaddit\deaddit\loader.py", line 336, in main
    create_comment()
  File "C:\Users\***\Downloads\deaddit\deaddit\loader.py", line 224, in create_comment
    post_id = random.choice(posts)["id"]
  File "C:\Users\***\AppData\Local\Programs\Python\Python310\lib\random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range
```
I've already ran "curl -X POST -H "Content-Type: application/json" -d "@deaddit/data/subdeaddits_base.json" http://localhost:5000/api/ingest" as per the usage instructions and I'm not sure if I'm doing anything wrong. Thank you in advance for responding back.

**Comment by cubicalbatch** [comment]
Thanks for the report!
It was trying to add a comment while there was no post. I have fixed up the code so that it creates a post if there are none - please pull and retry
